### PR TITLE
Fix numpy 1.20 deprecation warnings

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Replaced
* np.bool with np.bool_,
* np.complex with np.complex128
* np.object with np.object_, and
* np.str with np.str_.

According to https://numpy.org/doc/stable/release/1.20.0-notes.html,
this will have no effect except to suppress deprecation warnings.

### CODE REVIEW

**Comment by emilyfertig** [comment]
Thanks for the PR! I talked to our TL some about this, and there’s more we want to understand about how this interacts with the Numpy versions we support internally and externally, and how it might affect TFP’s JAX and Numpy backends (and we might prefer to use `bool` instead of `np.bool_`, etc., where possible.) We’ll update once we’ve looked into it more.

**Comment by NeilGirdhar** [comment]
@emilyfertig Sure, sounds good.

**Comment by NeilGirdhar** [comment]
Regarding JAX though, they made the same changes a while ago (https://github.com/google/jax/pull/3525).

**Comment by NeilGirdhar** [comment]
@emilyfertig Any luck?

**Comment by NeilGirdhar** [comment]
@emilyfertig Sorry if I'm being a bit of a nag, but I'd like to make sure these warnings disappear before the next release is packaged.  I think this should really be a completely transparent change and an easy code review.

**Comment by NeilGirdhar** [comment]
For context, this is what the warnings look like on the console:
```sh
pytest tests/test_simplified_encoding.py                                                                                           ✔  cmm-tspD8tmv-py3.9  
========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/neil/src/cmm
plugins: forked-1.3.0, xdist-2.2.1
collected 0 items / 1 error                                                                                                                                                                            

================================================================================================ ERRORS ================================================================================================
__________________________________________________________________________ ERROR collecting tests/test_simplified_encoding.py __________________________________________________________________________
ImportError while importing test module '/home/neil/src/cmm/tests/test_simplified_encoding.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.9.5/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_simplified_encoding.py:16: in <module>
    from cmm import (CodeMessage, EncodingElement, EncodingProblemBase, EncodingProblemState,
E   ImportError: cannot import name 'ExpFamSpace' from 'cmm' (/home/neil/src/cmm/cmm/__init__.py)
=========================================================================================== warnings summary ===========================================================================================
../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/flatbuffers/compat.py:19
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:511
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:511: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:553
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:553: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:563
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:563: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.bool,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/tensor_util.py:108
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/tensor_util.py:108: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object:

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/tensor_util.py:110
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/framework/tensor_util.py:110: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.bool:

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/ops/numpy_ops/np_random.py:110
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow/python/ops/numpy_ops/np_random.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    def randint(low, high=None, size=None, dtype=onp.int):  # pylint: disable=missing-function-docstring

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:569
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:569: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    (np.object, string),

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:570
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:570: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    (np.bool, bool),

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:594
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:594: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_STRING: np.object,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:598
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:598: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_BOOL: np.bool,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:615
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:615: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_STRING_REF: np.object,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:620
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:620: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    types_pb2.DT_BOOL_REF: np.bool,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/util/tensor_util.py:109
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/util/tensor_util.py:109: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object: SlowAppendObjectArrayToTensorProto,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/util/tensor_util.py:110
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorboard/util/tensor_util.py:110: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.bool: SlowAppendBoolArrayToTensorProto,

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/jax/numpy_array.py:282
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/jax/numpy_array.py:282: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    def _sequence_mask(lengths, maxlen=None, dtype=onp.bool, name=None):  # pylint: disable=unused-argument

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/jax/dtype.py:83
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/jax/dtype.py:83: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    bool = onp.bool  # pylint: disable=redefined-builtin

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/numpy/numpy_array.py:281
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/numpy/numpy_array.py:281: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    def _sequence_mask(lengths, maxlen=None, dtype=np.bool, name=None):  # pylint: disable=unused-argument

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/numpy/dtype.py:82
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/numpy/dtype.py:82: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    bool = np.bool  # pylint: disable=redefined-builtin

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/numpy/dtype.py:112
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/python/internal/backend/numpy/dtype.py:112: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    string = getattr(np, 'str', getattr(np, 'string', None))

../../.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/substrates/jax/mcmc/sample_halton_sequence.py:383
  /home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.9/lib/python3.9/site-packages/tensorflow_probability/substrates/jax/mcmc/sample_halton_sequence.py:383: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    sieve = np.ones(n // 3 + (n % 6 == 2), dtype=np.bool)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================= short test summary info ========================================================================================
ERROR tests/test_simplified_encoding.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================================== 21 warnings, 1 error in 3.20s =====================================================================================
```

**Comment by NeilGirdhar** [comment]
@brianwa84 Are you able to do a quick code review?

**Review by brianwa84 — APPROVED** [review]
I'll try to pull this in, hopefully our internal numpy version is modern enough. :)

**Pull request merged**
