### PR TITLE
Update math module reference in API documentation

### PR DESCRIPTION
**Pull request by gameshamilton**

### CODE REVIEW

**Comment by srvasude** [comment]
Hi,
  Thanks for the change! Do you mind making it instead to the corresponding python file? We generate our markdown files from the python files.

**Comment by srvasude** [comment]
Can you remove the markdown change?

**Comment by gameshamilton** [comment]
It seems there is still an ``` change on the .md file. Should I address that? Apologies.

**Comment by srvasude** [comment]
Yes please. Thanks!

**Pull request merged**
