### PR TITLE
probability: minor spelling tweaks

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Comment by jvdillon** [comment]
Great! Thanks for the fixes!

**Comment by jvdillon** [comment]
Thanks again for your contribution! Ive merged your PR.

**Comment by dustinvtran** [comment]
Is there any way to have the system automatically close the PR, link to the commit, and conversely, have the commit link to the PR? This referencing is useful for posterity.

**Comment by jvdillon** [comment]
It actually might do this. I closed this PR not realizing that the internal
submit was ongoing.

**Comment by dustinvtran** [comment]
Did it work for this PR? https://github.com/tensorflow/probability/pull/18 https://github.com/tensorflow/probability/commit/b46b1210dcd360b052799c81b8f84ad09d018c02

**Comment by jvdillon** [comment]
On Fri, Apr 13, 2018 at 1:12 PM, Dustin Tran <notifications@github.com>
wrote:

> Did it work for this PR? #18
> <https://github.com/tensorflow/probability/pull/18> b46b121
> <https://github.com/tensorflow/probability/commit/b46b1210dcd360b052799c81b8f84ad09d018c02>
>
Sadly, no. It appears we do have to manually close.

**Comment by dustinvtran** [comment]
Ah, I see. I'll raise a feature request about this.

**Pull request closed without merging**
