### PR TITLE
Deepcopy of weak structure references

### PR DESCRIPTION
**Pull request by awav**
This PR addresses issues at https://github.com/tensorflow/probability/issues/547 and https://github.com/tensorflow/probability/issues/944 by defining [`__deepcopy__`](https://docs.python.org/3/library/copy.html#copy.deepcopy) method of the `WeakStructureRef` class, that holds a structure with `HashableWeakRef`s. However, there are many nuances about `weakrefs`, and it seems impossible to provide complete deepcopy support.

The current version of deepcopy works well with tensors - simply because deepcopy returns the same tensor. When we apply deepcopy on a numpy array we get a new version of it and the reference count for the copy is one. For a deep copy of a weak structure reference, we also wrap the new numpy array with `weakref` and its reference count inside `__deepcopy__` is one. The numpy array lifetime is limited to the scope of the `__deepcopy__` method. Once we exit `__deepcopy__`, the reference count is down to 0, and the `weakref` changes its status to "dead".

```python
import tensorflow as tf
import numpy as np

ndarray = np.zeros([2, 3])
tensor = tf.constant([1., 2., 3.])
ref1 = WeakStructRef(tensor, subkey='b')
ref2 = WeakStructRef(ndarray, subkey='a')

ref1_copy = deepcopy(ref1)  # new weak reference, but the same tensor
ref2_copy = deepcopy(ref2)  # new weak reference and dead status

# Trick to make a weak reference alive
memo = {}  # retains a copy of the ndarray, therefore the reference count is 1
ref2_copy = deepcopy(ref2, memo)  # alive weak reference
```

The alternative method would be: never copy a cache and leave it empty.

Offtopic: I would appreciate if somebody could explain how to setup vscode or pycharm to run tests from `tensorflow_probability`. Thanks.

### CODE REVIEW

**Comment by csuter** [comment]
Thanks for working on this fix @awav! I think a trivial __deepcopy__ implementation that doesn't try to persist the cache contents is probably the best approach here. Copying in-process is likely rare, and in the primary problematic use case of serialization/deserialization I think re-animating weakrefs in the cache will be unhelpful (indeed, as you note, they will just be cleaned up when the copying is over).

For testing, we use bazel; I'm not sure about IDE integration, but the scripts in the top-level testing/ dir may be useful guides. Note the run_tests.sh script is complicated by the fact that it 1. is written to run on Travis and 2. is written to shard tests (taking size into account) to improve overall latency on Travis. Anyway, the commands you'd need to run are suggested there -- note the bazel flags, some of which are crucial.

**Comment by awav** [comment]
Hello @csuter. I made a custom `__deepcopy__` method for bijectors. Other solutions are very fragile. The bijector's cache contains function closures. I added a test case, but Travis fails in a different place and the error is not obvious. Could you take a look?

**Comment by nathanhack** [comment]
@csuter, @awav  is there any status on this feature?

**Comment by awav** [comment]
Hi, @nathanhack. The PR is more or less done, it is up to the TFP team to merge it or not, or give feedback :)

**Comment by awav** [comment]
@csuter, What's the status of the review for this PR? Can someone take a look and tell what needs to be done?

I keep getting "hashable" errors at deep copying TFP objects. They are  especially hard to handle because of differences between versions 0.10 and 0.11

**Comment by st--** [comment]
I'd be really keen for this to get merged. As it stands, we need to maintain very implementation-specific workarounds in our downstream code in GPflow that we have to keep updating (https://github.com/GPflow/GPflow/pull/1553, https://github.com/GPflow/GPflow/pull/1574) to ensure continued compatibility with tensorflow-probability...

**Comment by csuter** [comment]
Apologies for the lapse @awav -- I went on parental leave at the end of June and this totally slipped off my radar. Thanks for keeping up with it, and tracking the recent (substantial) changes to bijector fundamentals. This basically LGTM; I'm going to ask @emilyfertig to have a pass as well.

**Review by csuter — COMMENTED** [review]
Sorry thought I sent these comments earlier!

**Comment by emilyfertig** [comment]
Hi @awav -- Thanks for the fix to this, and sorry we weren't on top of it over the summer! 

We've made a major change to bijector caching since the 0.11 release, where bijectors now access a shared global cache, instead of maintaining instance-level caches. With these changes, in the nightly build, I can't seem to reproduce any deepcopy/pickle errors (including the examples in #547 and #944). 

If the deepcopy issue is indeed resolved at head (and will go into the 0.12 release, probably within a couple months, following TF's release), is there anything you'd still want merged? Or would it be sufficient if we add a unit test to confirm that deepcopy works on bijectors?

(Also, related to the example above, I'm curious as to when Numpy arrays are wrapped in `WeakStructRef`s -- Bijector methods call `tf.convert_to_tensor` on their inputs, so in TFP library code, I think `WeakStructRef` will only wrap `Tensor`s, unless you're using TFP's Numpy backend).

**Comment by emilyfertig** [comment]
Closing since `deepcopy` now works for bijectors, following global caching changes.

**Pull request closed without merging**
