### PR TITLE
Delete inappropriate tags in sample code.

### PR DESCRIPTION
**Pull request by pshiko**
Fixed a typo where syntax highlighting was not performed correctly because inappropriate tags were mixed in the sample code.
I do not know why this tag exists.
I am sorry if it is an incorrect fix or if it has already been fixed.

### CODE REVIEW

**Comment by csuter** [comment]
Thanks for the PR, but actually these api docs are auto-generated from the python docstrings, so to fix we need to make the change in the python code, then internally we can rebuild and push the docs update. Do you mind moving the change to the python source?

**Comment by pshiko** [comment]
Of course.
However, when I confirmed the source, docstring seems to have no problem.
This appears to be a bug in gdoc3 when generating tags in doxygen format.
I confirmed the same problem even in tfp.glm.fit_sparse md.
Since I do not have any knowledge about gdoc 3's problem, can you please fix it?

**Comment by csuter** [comment]
Ah, I see. Thanks very much for bringing this to our attention. We'll iterate on our internal tools and hopefully have a fix out soon!

**Comment by MarkDaoust** [comment]
Yes. Thanks for the report.

It appears the problem is in the tool that parses doc-strings to markdown, where it tries to convert Args/Returns/Raises blocks.

https://github.com/tensorflow/docs/blob/9aa6df82399c4fbca552af98d42c6332ca4614be/tools/tensorflow_docs/api_generator/parser.py#L427

I'll look into a fix.

**Pull request closed without merging**
