### PR TITLE
style tweak of SliceSampler document

### PR DESCRIPTION
**Pull request by wataruhashimoto52**

### CODE REVIEW

**Comment by wataruhashimoto52** [comment]
I signed it!

**Comment by dustinvtran** [comment]
Thanks for the fix. Note the `md` files are automatically rendered. Can you find the appropriate docstring in the slice sampler code to fix?

**Comment by wataruhashimoto52** [comment]
Yes, I fixed the display range of docstring of slice sampler code.

Before: https://www.tensorflow.org/probability/api_docs/python/tfp/mcmc/SliceSampler 

After: 
screen shot 2018-09-02 at 11 08 46

**Comment by saxena-ashish-g** [comment]
Note that this issue was fixed in this [commit](https://github.com/tensorflow/probability/commit/076ae0729d43470f0a7db1c3df89eb0416dc3023). I don't know how often the pages at api_docs are regenerated but whenever it happens next, you should be able to see the fixed page.

**Comment by dustinvtran** [comment]
Marking closed as @saxena-ashish-g already fixed. Thanks for the PR though!

**Pull request closed without merging**
