### PR TITLE
Added 10 example notebooks (based on Edward1)

### PR DESCRIPTION
**Pull request by matthew-mcateer**
Added a Jupyter notebook for a doubly-stochastic Poisson process, with the example being simulating the numbers of shots taken from positions on a Basketball Court by 308 NBA Players.

### CODE REVIEW

**Comment by matthew-mcateer** [comment]
Just added another PR for the addition of the Probabilistic matrix Factorization notebook (also available in colab form).

**Comment by matthew-mcateer** [comment]
Added 5 more noteooks (bringing the total to 7 now)

**Comment by twiecki** [comment]
Is Edward1 still maintained?

**Comment by matthew-mcateer** [comment]
@twiecki No, Edward1 is not still maintained. Edward1 only works up to Tensorflow 1.5 (The most recent version is Tensorflow 1.12). Edward1 hasn't been maintained in a long time, apparently. Plus, several of the members of the Edward1 team are on the Tensorflow team, and Tensorflow Probability contains "Edward2".

**Comment by twiecki** [comment]
Why this port then?

**Comment by csuter** [comment]
IIUC, this is translating examples from Ed1 to pure TFP (no Ed1 or Ed2).

**Comment by matthew-mcateer** [comment]
@twiecki it's not really a port. It's just that those are good example problems for which to demonstrate solutions in a variety of different languages, TFP included.

**Comment by matthew-mcateer** [comment]
There are now 11 Commits in this PR. They are as follows:

- [Probabilistic Matrix Factorization](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/probabilistic_matrix_factorization_in_tfp.ipynb)
- [Factor Analysis](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Factor_Analysis_TFP.ipynb)
- [Cox Process](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Cox_Process.ipynb)
- [Supervised Classification](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Supervised_Classification_with_GP_TFP.ipynb)
- [Deep Exponential Family](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Deep_Exponential_Family_TFP.ipynb)
- [Mixture Denisty Networks](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Mixture_Density_Network_TFP.ipynb)
- [LSTM](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/LSTM_TFP.ipynb)
- [Sigmoid belief network](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Sigmoid_Beleif_Network_TFP.ipynb)
- [Rasch Model](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Rasch_Model_TFP.ipynb)
- [Stochastic Block Model](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Stochastic_Block_Model_TFP.ipynb)
- [Latent Space Models](https://github.com/tensorflow/probability/blob/a4d1fbc131880ed3ffa83fe83b1d2583da90f294/tensorflow_probability/examples/jupyter_notebooks/Latent_Space_Models_TFP.ipynb)

**Comment by matthew-mcateer** [comment]
Thank you, @sridatta I will respond to those comments you made. Were there any others in the other jupyter notebooks?

**Comment by sridatta** [comment]
I'm working my way through them. I'll do a couple everyday and edit my comment above. Once I've taken a look at all, I'll comment on this thread again.

**Comment by sridatta** [comment]
My only comment on Sigmoid belief model was to correct "beleif" to "belief" throughout the notebook :) I just interrupted the notebook because it was taking a while

**Comment by matthew-mcateer** [comment]
Hey @sridatta, Not sure how long these checks are supposed to take (The Travis CI has been going on for a long LONG time now). Anyway, the Latent Space model is updated, the Sigmoid Belief misspellings were fixed, and the Sotchastic Block Model `RuntimeError`s were fixed. How's it looking now?

I also took a further look at the Deep Exponential Families. I've tried a bunch of different approaches to try and get it to converge faster, but I think the main problem is that even the original Edward1 example was truly gargantuan in terms of the task it was trying to complete. I feel like if the goal was creating short and simple demos, the Deep Exponential Families was a bad choice. Do you think just a note/warning will be enough, @sridatta?

**Comment by matthew-mcateer** [comment]
Okay, @sridatta, I removed the Deep Exponential Family, and I'm going to add it to another PR. I'm doing this because it seems that that's the only one that needs further editing. I figure we should at least commit the other 10 if they work, so we have something to show.

I also have the CAPM example in another PR.

**Comment by sridatta** [comment]
LGTM

**Comment by srvasude** [comment]
Hi Matthew,
   Thanks for your patience!! It'll take some time to go through these notebooks, and in order to expedite things, may I ask a few things?:

@sridatta : Can you make your colabs commentable? Reviewing there (@csuter is there a better way to do this review?). Specifically I can not comment on the Sigmoid Belief, Rasch Model. Weirdly I'm not able to load the other notebooks, although that might just be a transient bug.

@matthew-mcateer : I'd strongly encourage / recommend splitting up this commit in to one pull request per colab. This is because it would make it easier for our internal review, since we can distribute the notebooks among our team, and speed up getting these in.


Some general comments on the colabs:

- There's a CSS cell at the end of each colab, which I'd recommend getting rid of (not sure what it does / doesn't seem applicable)
- I notice that each colab has quite a bit of boilerplate (Copyright, License, Ported line and Dependencies / Prerequisites). I'm wondering how much of that is necessary. I'll ask around internally once we start reviews. If it's the case that there is boilerplate that we can factor out, we can make a colab template, that we just import at the top (%run template.ipynb).

**Comment by matthew-mcateer** [comment]
Hi @srvasude,
Thanks for the info. I think you're right. I will split up these notebooks among several PRs. I will also delete the CSS cell at the end (this was often a feature with the bayesian hacker notebooks, so it was added in by default), whereas the boilerplate code was added into cells which were hidden as Colabs (though this doesn't really work with JuPyter notebooks). I will work on these issues and then resubmit as new PRs.

**Comment by matthew-mcateer** [comment]
@srvasude @sridatta Hey, If you look in the Pull Requests, I just made a bunch of distinct PRs for every single TFP example.

**Comment by srvasude** [comment]
Thanks for sharding! I'll be taking a look at these later today.

**Pull request closed without merging**
