### PR TITLE
Fix typos in documentation for smoothing

### PR DESCRIPTION
**Pull request by mjul**
Fix typos by adding the missing 1

### CODE REVIEW

**Comment by jeffpollock9** [comment]
Hi @mjul. AFAIK the markdown files you've edited are automatically generated from the docstrings in the corresponding .py files - so better to make the changes there instead.

**Comment by mjul** [comment]
@jeffpollock9 Thanks for the advice, I have updated the PR accordingly.

**Comment by srvasude** [comment]
Hi,
  Would you please remove the changes to the .md files? PR looks good otherwise.

Also, we will be removing the .md files soon, since we have nightly docs generated from the docstrings now.

**Comment by mjul** [comment]
OK, @srvasude, I have rebased and dropped the commit to the .md files as requested.

**Pull request merged**
