### PR TITLE
Imported missing matplotlib.pyplot

### PR DESCRIPTION
**Pull request by uzair-ali10**
matplotlib.pyplot wasn't imported so i added 
`"import matplotlib.pyplot as plt\n",`

### CODE REVIEW

**Comment by uzair-ali10** [comment]
Why these checks are failing??

**Comment by NeilGirdhar** [comment]
@uzair-ali10 I think the failing checks would be fixed by https://github.com/tensorflow/probability/pull/1303, which the TFP team hasn't gotten around to reviewing

**Comment by uzair-ali10** [comment]
@NeilGirdhar 
Ohh is it??, so I guess ill wait for them to fix it up!! they seem to be very busy

**Comment by SiegeLordEx** [comment]
Sadly the github test issues are not that simple. Either way, this change looks fine, let me get it merged in. Sorry for letting this slip through the cracks.

**Pull request merged**
