### PR TITLE
Implemention of Mean Method in distributions.Categorical

### PR DESCRIPTION
**Pull request by PavanKishore21**
## Proposition for correcting issue #685 Error with Implementation of Mean Method in distributions.Categorical

> NotImplementedError: mean is not implemented: Categorical

```py
import tensorflow_probability as tfp

prob_dist = tfp.distributions.Categorical(probs=[1.0])
print(prob_dist.mean())

```

Defined a `_mean` method for implementing mean

### CODE REVIEW

**Comment by PavanKishore21** [comment]
@googlebot I signed it!

**Comment by SiegeLordEx** [comment]
This implementation is not correct. The mean of a categorical is defined as `sum(i * prob(x=i) for i in range(num_categories)`. You should be able to modify the implementation of the `_entropy` to implement this.

This will also need tests to verify the implementation is correct (entropy tests, again, should provide a good set of test cases).

**Comment by PavanKishore21** [comment]
Hello @SiegeLordEx, Thanks for your response.
I have updated the formula for Mean

`tf.reduce_sum(tf.math.multiply_no_nan(i , self._prob(x=i)) for i in range(self._num_categories), axis=-1`

Check this out

**Comment by fotisdr** [comment]
The previous implementation was incorrect. I've written an example implementation of how the Categorical mean should be like, the code below works for me and produces the desired result. The mean should also account for unnormalised probabilities between the classes, since there are cases where the probabilities don't sum up to 1. 
```python
  def _mean(self):
    probs = self.probs_parameter()
    num_categories = self._num_categories(probs)
    # Initialise the mean with zeros
    categorical_mean = tf.zeros(tf.shape(probs[...,0]))
    # Compute the normalisation factors such that all probabilities sum up to 1
    normalisation = tf.reduce_sum(probs, axis=-1)
    # Sum up all the normalised probabilities
    # sum(i * prob(X=i) for i in range(num_categories) )
    for i in range(num_categories):
    	categorical_mean = categorical_mean + tf.cast(i,probs.dtype) * probs[...,i] / normalisation
    
    return categorical_mean
``` 
Shall I make a new commit for this?

**Comment by fotisdr** [comment]
> I don't think there is currently an implementation. The following might be simpler: tf.reduce_sum(tf.range(self._num_categories(probs)) * probs, axis=-1) / tf.reduce_sum(probs, axis=-1) You could send a PR, sure.

Hi, 
Indeed this looks much simpler, thanks! We want to ensure that the multiplication is applied across the last axis of probs, i.e. each slice of probs across the last dimension (probs[...,i]) gets multiplied by each number i in tf.range(self._num_categories(probs)). The multiplication should be doing this by default, but I will test the code and submit a new PR.

**Comment by SiegeLordEx** [comment]
This got implemented in b14ae1d79de4a52d834a3ba2dc88f7e5d849e6c7.

**Pull request closed without merging**
