### PR TITLE
Fix typo in real_nvp.py

### PR DESCRIPTION
**Pull request by emiliojorge**
Fixing a small typo in spelling of memorizes in real_nvp.py

### CODE REVIEW

**Comment by emiliojorge** [comment]
`I signed it!`

**Comment by SiegeLordEx** [comment]
That's actually correct as is, the comment means this https://en.wikipedia.org/wiki/Memoization. Thanks for reaching out!

**Comment by brianwa84** [comment]
Arguably memoize is a bad word here, though, because it's not [exactly] like we are sometimes doing work, sometimes using cached work.
Perhaps "specializes the bijector for `D`" or "initializes weights matching size `D`".

**Comment by SiegeLordEx** [comment]
The related internal function is literally called 'cache', so 'caches' is possibly the right verb. @emiliojorge , if you're interested, you could change it to that and we'll merge this change in :).

**Pull request closed without merging**
